In [11]:
! pip install quandl

Collecting quandl
  Downloading https://files.pythonhosted.org/packages/6f/b9/237394fb7f23fd0233bc5c39a2f1c74d4c24850932762ff51be5be20269c/Quandl-3.4.4-py2.py3-none-any.whl
Requirement already satisfied: pandas>=0.14 in c:\users\bruce\anaconda3\lib\site-packages (from quandl) (0.23.0)
Requirement already satisfied: more-itertools in c:\users\bruce\anaconda3\lib\site-packages (from quandl) (4.1.0)
Requirement already satisfied: requests>=2.7.0 in c:\users\bruce\anaconda3\lib\site-packages (from quandl) (2.18.4)
Requirement already satisfied: numpy>=1.8 in c:\users\bruce\anaconda3\lib\site-packages (from quandl) (1.14.3)
Requirement already satisfied: six in c:\users\bruce\anaconda3\lib\site-packages (from quandl) (1.11.0)
Collecting inflection>=0.3.1 (from quandl)
  Downloading https://files.pythonhosted.org/packages/d5/35/a6eb45b4e2356fe688b21570864d4aa0d0a880ce387defe9c589112077f8/inflection-0.3.1.tar.gz
Requirement already satisfied: python-dateutil in c:\users\bruce\anaconda3\lib\site-packages (from quandl) (2.7.3)
Requirement already satisfied: pytz>=2011k in c:\users\bruce\anaconda3\lib\site-packages (from pandas>=0.14->quandl) (2018.4)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\bruce\anaconda3\lib\site-packages (from requests>=2.7.0->quandl) (3.0.4)
Requirement already satisfied: idna<2.7,>=2.5 in c:\users\bruce\anaconda3\lib\site-packages (from requests>=2.7.0->quandl) (2.6)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in c:\users\bruce\anaconda3\lib\site-packages (from requests>=2.7.0->quandl) (1.22)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\bruce\anaconda3\lib\site-packages (from requests>=2.7.0->quandl) (2018.4.16)
Building wheels for collected packages: inflection
  Running setup.py bdist_wheel for inflection: started
  Running setup.py bdist_wheel for inflection: finished with status 'done'
  Stored in directory: C:\Users\bruce\AppData\Local\pip\Cache\wheels\9f\5a\d3\6fc3bf6516d2a3eb7e18f9f28b472110b59325f3f258fe9211
Successfully built inflection
Installing collected packages: inflection, quandl
Successfully installed inflection-0.3.1 quandl-3.4.4

distributed 1.21.8 requires msgpack, which is not installed.
You are using pip version 10.0.1, however version 18.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

In [15]:
#Dependencies and api_keys
import requests
from pprint import pprint
from config import quandl_key
import json

#API That Pulls Data From Zillow Monthly
#API Doc https://www.quandl.com/data/ZILLOW-Zillow-Real-Estate-Research/documentation/data-organization
#Register for account to get API Key (found on your profile)
import quandl

In [16]:
#Set API Key
quandl.ApiConfig.api_key = quandl_key

#Pull Table (DF?) Based On Code(ZILLOW/search-type[Z for zip-code]|search-value[94303]|_|
#type-of-value(ex.home-value-index, find list of options in documentation)
quandl.get('ZILLOW/Z94303_ZHVIAH', column_index='1')

                Value
Date
1996-04-30   337300.0
1996-05-31   338100.0
1996-06-30   339200.0
1996-07-31   340500.0
1996-08-31   342100.0
1996-09-30   344100.0
1996-10-31   346700.0
1996-11-30   349900.0
1996-12-31   354000.0
1997-01-31   358900.0
1997-02-28   364300.0
1997-03-31   370200.0
1997-04-30   376600.0
1997-05-31   383200.0
1997-06-30   389700.0
1997-07-31   395900.0
1997-08-31   401700.0
1997-09-30   406900.0
1997-10-31   411400.0
1997-11-30   415300.0
1997-12-31   418700.0
1998-01-31   421700.0
1998-02-28   424100.0
1998-03-31   425800.0
1998-04-30   427200.0
1998-05-31   428300.0
1998-06-30   429300.0
1998-07-31   430000.0
1998-08-31   430600.0
1998-09-30   431200.0
...               ...
2016-04-30  1721900.0
2016-05-31  1735300.0
2016-06-30  1742300.0
2016-07-31  1735200.0
2016-08-31  1731600.0
2016-09-30  1740400.0
2016-10-31  1737400.0
2016-11-30  1721400.0
2016-12-31  1730200.0
2017-01-31  1767000.0
2017-02-28  1783000.0
2017-03-31  1772300.0
2017-04-30  1764000.0
2017-05-31  1776100.0
2017-06-30  1825600.0
2017-07-31  1881100.0
2017-08-31  1891000.0
2017-09-30  1878600.0
2017-10-31  1903600.0
2017-11-30  1952900.0
2017-12-31  1987400.0
2018-01-31  2019300.0
2018-02-28  2066100.0
2018-03-31  2096100.0
2018-04-30  2093000.0
2018-05-31  2081700.0
2018-06-30  2060700.0
2018-07-31  2018200.0
2018-08-31  1987300.0
2018-09-30  1989000.0

[270 rows x 1 columns]

In [10]:
print(result)

19501259